[tool.poetry]
name = "bento-tools"
packages = [{ include = "bento" }]
include = [
    "bento/datasets/datasets.csv",
    "bento/models/**/*",
    "bento/tools/gene_sets/*",
]
version = "2.1.0a0"
description = "A toolkit for subcellular analysis of spatial transcriptomics data"
authors = ["Clarence Mah <ckmah@ucsd.edu>"]
license = "BSD-2-Clause"
readme = "README.md"

[tool.poetry.dependencies] # TODO readd all dependencies
# adjustText = "^0.7.3"
# anndata = "^0.9.2"
# astropy = "^5.0"
# decoupler = "1.4.0"
# emoji = "^1.7.0"
# kneed = "^0.8.1"
# matplotlib = "~3.7"
# matplotlib-scalebar = "^0.8"
# MiniSom = "^2.3.0"
# myst-nb = {version = "^0.17.1", extras = ["docs"]}
# pandas = "^1.5.3"
python = ">=3.9"
# rasterio = "^1.3.0"
# rtree = "^1.0.1"
# scanpy = "^1.9.1"
# scipy = "^1.7.0"
# seaborn = "^0.12.1"
# Shapely = "^2.0.1"
# sparse = "^0.15.0"
# spatialdata = "0.1.2"
# Sphinx = { version = "^7.0", extras = ["docs"] }
# sphinx_design = {version = "^0.5.0", extras = ["docs"]}
# sphinx-autobuild = { version = "^2021.3.14", extras = ["docs"] }
# sphinx-book-theme = {version = "^1.0.0", extras = ["docs"] }
# sphinx-gallery = { version = "^0.10.1", extras = ["docs"] }
# statsmodels = "^0.13.2"
# tensorly = "^0.7.0"
# tqdm = "^4.64.0"
# UpSetPlot = "^0.6.1"
# xgboost = "2.0.0"

[tool.poetry.extras]
docs = [
    "Sphinx",
    "sphinx-autobuild",
    "sphinx-book-theme",
    "myst-nb",
    "sphinx_design",
]

[tool.setuptools]
py_modules = []

[build-system]
requires = ["poetry-core>=1.0.0", 'setuptools']
build-backend = "poetry.core.masonry.api"
